CREATE TABLE IF NOT EXISTS test_runs (
    id SERIAL PRIMARY KEY,
    repo_url VARCHAR(255) NOT NULL,
    branch VARCHAR(100) NOT NULL,
    status VARCHAR(50) DEFAULT 'PENDING',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

